spring:
    datasource:
        url: jdbc:mysql://database-2.cdgiiabcm6en.us-east-1.rds.amazonaws.com:3306/edwiki?createDatabaseIfNotExist=true
        username: admin
        password: admin123
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: create
        show-sql: true
        generate-ddl: false
  # Producer properties
    kafka:
      bootstrap-servers: 127:0:0:1:9092
      group-id: group_id
topic:
  name:
    producer: topico.comando.teste
    consumer: topico.teste
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false
        credentials:
            accessKey: AKIAYMMFC5FDUATWA6PN
            secretKey: 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

application:
    bucket:
        name: edwiki-webserver-config

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

baseUrl: http://localhost:5555/v1
