spring:
    datasource:
        url: jdbc:mysql://localhost:3306/edwiki?createDatabaseIfNotExist=true
        username: root
        #password: C@$R@k2020
        password: Ascorp@123
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: none
        show-sql: true
        generate-ddl: false
  # Producer properties
    kafka:
      producer:
        bootstrap-servers: 127:0:0:1:9092
        key-serializer:
          org:apache:
            kafka:
              common:
                serialization: StringSerializer
        value-serializer:
          org:apache:
            kafka:
              common:
                serialization: StringSerializer
        group-id: group_id
topic:
  name:
    producer: topico.comando.teste
    consumer: topico.teste
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false
        credentials:
            accessKey: AKIAYMMFC5FDXJR2R5FO
            secretKey: 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

application:
    bucket:
        name: edwiki-webserver-config

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

baseUrl: http://localhost:5555/v1
