spring:
    datasource:
        url: jdbc:mysql://localhost:3306/edwiki?createDatabaseIfNotExist=true
        username: root
        password: C@$R@k2020
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: none
        show-sql: true
        generate-ddl: false
  # Producer properties
    kafka:
      producer:
        bootstrap-servers: 127:0:0:1:9092
        key-serializer:
          org:apache:
            kafka:
              common:
                serialization: StringSerializer
        value-serializer:
          org:apache:
            kafka:
              common:
                serialization: StringSerializer
        group-id: group_id
topic:
  name:
    producer: topico.comando.teste
    consumer: topico.teste
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    gateway:
        routes:
        - id: catalog-service
          uri: lb://catalog-service/
          predicates:
          - Path=/v1/catalog/**
        - id: kart-service
          uri: lb://kart-service/
          predicates:
          - Path=/v1/kart/**
        - id: payment-service
          uri: lb://payment-service/
          predicates:
          - Path=/v1/payment/**
        - id: order-service
          uri: lb://order-service/
          predicates:
          - Path=/v1/order/**
        - id: user-service
          uri: http://localhost:8085/
          predicates:
          - Path=/v1/user/**
    aws:
        region:
            static: ap-south-1
        stack:
            auto: false
        credentials:
            accessKey: AKIA32CIHYHAOT2KHV
            secretKey: fcmvvq1hcDoSWmHSem6VRc6GdHw2081lUawajH

application:
    bucket:
        name: techgeeknextbucket

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false
    hostname: localhost
